<?php

namespace ContainerIZ8ToY2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IISxcVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iISxc_V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iISxc_V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'detailRepository' => ['privates', 'App\\Repository\\DetailRepository', 'getDetailRepositoryService', true],
        ], [
            'detailRepository' => 'App\\Repository\\DetailRepository',
        ]);
    }
}
