<?php

namespace ContainerIZ8ToY2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetail2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.W_ttCrJ.App\Entity\Detail' shared service.
     *
     * @return \App\Entity\Detail
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.W_ttCrJ": it needs an instance of "App\\Entity\\Detail" but this type has been excluded in "config/services.yaml".');
    }
}
