<?php

namespace ContainerIZ8ToY2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetailTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DetailType' shared autowired service.
     *
     * @return \App\Form\DetailType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DetailType.php';

        return $container->privates['App\\Form\\DetailType'] = new \App\Form\DetailType();
    }
}
