<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIZ8ToY2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIZ8ToY2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIZ8ToY2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIZ8ToY2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIZ8ToY2\App_KernelDevDebugContainer([
    'container.build_hash' => 'IZ8ToY2',
    'container.build_id' => 'dd855608',
    'container.build_time' => 1692695735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIZ8ToY2');
