<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_detail_index' => [[], ['_controller' => 'App\\Controller\\DetailController::index'], [], [['text', '/detail/']], [], [], []],
    'app_detail_new' => [[], ['_controller' => 'App\\Controller\\DetailController::new'], [], [['text', '/detail/new']], [], [], []],
    'app_detail_show' => [['id'], ['_controller' => 'App\\Controller\\DetailController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/detail']], [], [], []],
    'app_detail_edit' => [['id'], ['_controller' => 'App\\Controller\\DetailController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/detail']], [], [], []],
    'app_detail_delete' => [['id'], ['_controller' => 'App\\Controller\\DetailController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/detail']], [], [], []],
    'app_order_index' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order/']], [], [], []],
    'app_order_new' => [[], ['_controller' => 'App\\Controller\\OrderController::new'], [], [['text', '/order/new']], [], [], []],
    'app_order_show' => [['id'], ['_controller' => 'App\\Controller\\OrderController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/order']], [], [], []],
    'app_order_edit' => [['id'], ['_controller' => 'App\\Controller\\OrderController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/order']], [], [], []],
    'app_order_delete' => [['id'], ['_controller' => 'App\\Controller\\OrderController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/order']], [], [], []],
    'app_product_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/']], [], [], []],
    'app_product_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new']], [], [], []],
    'app_product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], [], []],
    'app_user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/new']], [], [], []],
    'app_user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
];
